### ISSUE TITLE
Я конечно все понимаю.... Но

### ISSUE THREAD

**Issue by nais2008** [MCtop4ik/go-first-sprint#1]
![image](https://github.com/user-attachments/assets/7356c562-1a77-4e26-8a76-b246adfb26b4)

Нигде не упоминается про не поддерживание пробелов, я был очень удивлен

**Comment by MCtop4ik** [comment]
лол
я код калькулятора скопировал из урока, он оказался полунерабочим) я с дробями увидел и деление на ноль только, рил надо все покрыть тестами

**Comment by MCtop4ik** [comment]
ХАХАХАХАХАХ еман, он очень странный

**Comment by nais2008** [comment]
не удивлен)

**Comment by MCtop4ik** [comment]
я думал там то нормальный код дали, просто свой я использовать не оч хочу, потому что там я по факту написал собственный язык программирования на го

**Comment by MCtop4ik** [comment]
ну типо менторы.... ну типо не ноунеймы...... ну типо проверяли бы.......

**Comment by nais2008** [comment]
первое правило программистов: не доверяй другим программистам

**Comment by rptl8sr** [comment]
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/34d74087-1103-49db-a54f-2e526549615a" />
да, считает прекрасно)) из-за того, что пробелы не пропускает, а как-то по своему интерпретирует

по факту:
1) нет тестов, а явно надо
2) лучше прям пример в курле писать, а не только в виде нагрузки, как сейчас
3) по-хорошему таки тип контент на серваке задавать сразу, сейчас ответ по дефолту в Content-Type text/plain приходит, а подразумевается application/json
4) 
<img width="570" alt="image" src="https://github.com/user-attachments/assets/92b266b1-c86d-4877-bff1-c485a8b547a2" />
странный кейс

**Comment by MCtop4ik** [comment]
s это видно sign

**Comment by MCtop4ik** [comment]
ладно как я писал я с первого урока код для калькулятора скопировал

**Comment by MCtop4ik** [comment]
есть тупая идея просто в выражении все пробелы replace заменить, но мне чет не нравится это

**Comment by MCtop4ik** [comment]
там ваще где пробел continue...

**Comment by MCtop4ik** [comment]
кароче костыль поставил с заменой

**Comment by MCtop4ik** [comment]
этой фигни не должно больше быть

**Comment by rptl8sr** [comment]
1) тесты появились, ок

2) примеров в ридми нормальных так и нет — смысл чтобы можно было скопировать команду целиком, да запустить в терминале, а не писать самому curl -X … и добавлять тело из примера

3) добавь заголовок 
<img width="722" alt="image" src="https://github.com/user-attachments/assets/07acbe12-bcf5-4417-b307-9a468a543108" />
это не обязательно, но хороший тон

4) калькулятор пересобрал, круть )
